version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/restro
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: /scripts/stop.sh
      timeout: 10
      runas: ec2-user
  BeforeInstall:
    - location: /scripts/setup.sh
      timeout: 180
      runas: ec2-user
  AfterInstall:
    - location: /scripts/afterinstall.sh
      timeout: 360
      runas: ec2-user
  ApplicationStart:
    - location: /scripts/start.sh
      timeout: 30
      runas: ec2-user
